# Generated by Django 3.2.8 on 2021-11-28 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=100)),
                ('comments', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SCE_Proj.comment')),
            ],
            options={
                'db_table': 'Post',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=10)),
                ('posts', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SCE_Proj.post')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='SCE_Proj.user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='SCE_Proj.user'),
        ),
    ]
