# Generated by Django 3.2.8 on 2021-11-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCE_Proj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
