# Generated by Django 3.2.8 on 2021-11-29 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCE_Proj', '0002_tmp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tmp',
            table='tmp',
        ),
    ]
