# Generated by Django 3.2.8 on 2021-11-29 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCE_Proj', '0002_auto_20211128_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.DecimalField(decimal_places=1, max_digits=1)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default=None, upload_to=None),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ratings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SCE_Proj.rating'),
        ),
    ]
